# Generated by Django 4.1 on 2022-10-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
